name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Setup MySQL
      uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: '8.0'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Test on Sqlite3
      run: cd tests && go test -v ./...

    - name: Test on MySQL
      run: mysql -uroot -h127.0.0.1 -e 'CREATE DATABASE IF NOT EXISTS structquery;'
